# Generated by Django 4.1.5 on 2023-01-05 07:27

from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime
from django.contrib.auth.models import User
import json
import requests
from trend_app.models import Trend
from trend_app.models import Favorite


# def insert_user(apps, scheme_editor):
#   User = apps.get_model('test_db_app', 'User')
#   user1 = User(email = "nhat@gmail.com", password = "nhatnhat", first_name = "Quang", last_name = "Nhat", phone_number = "0934676767")
#   user1.save()

#----------------------------------------------------------------

def insert_location(apps, scheme_editor):
  # User = apps.get_model('test_db_app', 'User')
  locations = [{
    "code": '1',
    "name": 'Worldwide',
  },
  {
    "code": '23424984',
    "name": 'Vietnam',
  },
  {
    "code": '23424856',
    "name": 'Japan',
  },]

  Location = apps.get_model('trend_app', 'Location')
  Location.objects.all().delete()
  for location in locations:
    print("location code: ", location["code"], "\n")
    print("location name: ", location["name"], "\n")
    location_item = Location(location_code = location["code"], \
                             location_name = location["name"])
    location_item.save()

#----------------------------------------------------------------
endpoint = "https://api.twitter.com/1.1/trends/place.json?id="
headers = {"Authorization": "Bearer AAAAAAAAAAAAAAAAAAAAAGCIjwEAAAAAu%2FyPAplXAQl%2F9YZcj9Rg%2FOyJYBY%3DYWBqPDEl5vhHutWme759g1XFZGNFLKrHO6Jb2KNUFvCBtInRkq"}

def insert_trend(apps, scheme_editor):
  # User = apps.get_model('test_db_app', 'User')
  response_data = json.loads(json.dumps(requests.get(endpoint+"1", headers=headers).json())) #transform response data to json
  dict_trend = response_data[0]["trends"]
  
  current_datetime = datetime.now()
  Trend = apps.get_model('trend_app', 'Trend')
  Location = apps.get_model('trend_app', 'Location')

  location_foreign = Location.objects.get(location_code = "1")

  print(dict_trend)
  for trend in dict_trend:
    trend_item = Trend(trend_name = trend["name"], tweet_volume = int(trend["tweet_volume"]) if trend["tweet_volume"] != None else 9999 , \
                       day = current_datetime.strftime('%Y-%m-%d'), hour = current_datetime.strftime('%H'), \
                       location_id = location_foreign)
    trend_item.save()

#----------------------------------------------------------------
def insert_favorite(apps, scheme_editor):
  # User = apps.get_model('test_db_app', 'User')

  list_trends = []
  # for num in range(0,10):
  #   list_trends.append(Trend.objects.get(id=str(num)))

  user_instance = User.objects.get(id='1')
  print("user: ",user_instance.password)
  trend_instance = Trend.objects.get(id='1')
  print("trend_instance: ",type(trend_instance))


  favorite_item = Favorite(user_id = user_instance, trend_id = trend_instance)
  # favorite_item = Favorite()
  # favorite_item.user_id = user_instance
  # favorite_item.trend_id = trend_instance
  favorite_item.save()
  # for trend in list_trends:
  #   favorite_item = Favorite(user_id = user1, trend_id = trend)
  #   favorite_item.save()

#----------------------------------------------------------------

def insert_user(apps, scheme_editor):
  # User = apps.get_model('test_db_app', 'User')
  user1 = User.objects.get(id="1")
  print("user name of user 1 is: ",user1.username)

def insert_data(apps, scheme_editor):
  pass

class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('trend_app', '0001_initial')
  ]

  operations = [
    migrations.RunPython(insert_location, reverse_code=insert_location),
    migrations.RunPython(insert_trend, reverse_code=insert_trend),
    migrations.RunPython(insert_favorite, reverse_code=insert_favorite),
  ]